In [14]:
# Bibliotecas de uso geral
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [11]:
# Instânciando a classe do MinMaxScaler
minmax = MinMaxScaler()

# Conjunto artificial de amostras de características
X = np.asarray([[10,  30, 50],
                [4,   6,  7],
                [4.5, 7,  9.9],
                [6,   7,  8.7]])

# Escolhendo uma característica qualquer j
j = 2
xj = X[:, j]

# Normalizando a coluna xj
zj = minmax.fit_transform(xj.reshape(-1, 1))
zj

array([[1.        ],
       [0.        ],
       [0.06744186],
       [0.03953488]])

In [13]:
# Normalizando o conjunto todo
Xz = minmax.fit_transform(X)
Xz

array([[1.        , 1.        , 1.        ],
       [0.        , 0.        , 0.        ],
       [0.08333333, 0.04166667, 0.06744186],
       [0.33333333, 0.04166667, 0.03953488]])

In [15]:
# Instânciando a classe do StandardScaler
zscore = StandardScaler()

# Conjunto artificial de amostras de características
X = np.asarray([[10,  30, 50],
                [4,   6,  7],
                [4.5, 7,  9.9],
                [6,   7,  8.7]])

# Normalizando o conjunto todo
Xz = zscore.fit_transform(X)
Xz

array([[ 1.64530917,  1.73063862,  1.72920603],
       [-0.90226632, -0.64280863, -0.66165761],
       [-0.68996836, -0.54391499, -0.50041332],
       [-0.05307449, -0.54391499, -0.5671351 ]])